### ISSUE TITLE
👍 All is working now but someting doesnt work... 

### ISSUE THREAD

**Issue by KasaiKonoru** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#10]
If a **premium** user type "!afk user" or "!afk guild", 
an error comes:
![Screenshot_20210226_091237](https://user-images.githubusercontent.com/45830738/109273670-c84a7780-7812-11eb-8e54-760608bd09cd.jpg)

Thank you and well done!  👌

**AND A Question:**

Where or how can i change the refresh time/delay for the Progressionbar. (I mean the Update for the embeds in setups)

**Comment by Tomato6966** [comment]
You can change it in /handlers/functions function called: "edit_request_message_track_info"
there is a for loop like that: 
```for (let i = 0; i < 10; i++) {
        await new Promise((resolve) => {
          setTimeout(() => {
            resolve(2);
          }, 7.5 * 1000);
        });
        if (i >= 5) i = 0;
        const curplayer = client.manager.players.get(player.guild);
        if (!curplayer) {
          reset(track_info_msg, queue_info_msg);
          break;
        }
        edit_10_s_np(track_info_msg, track, queue_info_msg, client, curplayer)
      }```
      
      `7.5 * 1000` this is the delay, now its on 7.5 Seconds dont go under 5 tho!

**Comment by KasaiKonoru** [comment]
> 
> 
> You can change it in /handlers/functions function called: "edit_request_message_track_info"
> there is a for loop like that:
> 
> ```
>         await new Promise((resolve) => {
>           setTimeout(() => {
>             resolve(2);
>           }, 7.5 * 1000);
>         });
>         if (i >= 5) i = 0;
>         const curplayer = client.manager.players.get(player.guild);
>         if (!curplayer) {
>           reset(track_info_msg, queue_info_msg);
>           break;
>         }
>         edit_10_s_np(track_info_msg, track, queue_info_msg, client, curplayer)
>       }```
>       
>       `7.5 * 1000` this is the delay, now its on 7.5 Seconds dont go under 5 tho!
> ```

And the command works! Afk user/guild?

**Comment by Tomato6966** [comment]
What?

**Comment by KasaiKonoru** [comment]
> What?

Its the error in the other Issues. with the command
!afk

**Comment by Tomato6966** [comment]
Fixxed in todays release update https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/releases/tag/4.0.0

well i literally downloaded github's code and it worked so....................... u can watch it on my live stream at the end... https://youtu.be/_qyHqucO_wc
