### ISSUE TITLE
Cannot read property 'players' of undefined

### ISSUE THREAD

**Issue by liloko** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#102]
![image](https://user-images.githubusercontent.com/78354559/156199734-e15c3fd6-12cf-4b1d-affb-3e834055ad8c.png)
![image](https://user-images.githubusercontent.com/78354559/156199754-052314be-7705-4bf1-b089-e15cfbc5335f.png)
how to fix?

**Comment by liloko** [comment]
oh, i now understand how, BUT
why searching the song so long?

**Comment by Hevky** [comment]
could u help me bro??
