### ISSUE TITLE
Add mongo db 

### ISSUE THREAD

**Issue by pasindu20** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#105]
Enamp are getting more ram now add quickmongo/mongo db and sharding

**Comment by Tomato6966** [comment]
no time for it + it takes not much more ram.

if u need to shard, u just cant use enmap

**Comment by Tomato6966** [comment]
if u consider to use quickmongo use my fork of it https://github.com/Tomato6966/quickmongo it has an in memory cache..

**Comment by pasindu20** [comment]
> no time for it + it takes not much more ram.
> 
> if u need to shard, u just cant use enmap

if you have time create mongo+sharding also recreate with in quickmongo+sharding but i didn't know about after load all clusters/shards and load autoresume and some times db is duplication/can't find data mongo db get crash/high ping

i want after load all clusters/shards and load autoresume

**Comment by pasindu20** [comment]
> if u consider to use quickmongo use my fork of it https://github.com/Tomato6966/quickmongo it has an in memory cache..

this has some bugs i can't post issue on it open the issue posting thins
bug is if set prefix on bot database do not restart  ex- !setprefix 4 if i use 4setprefix its get undefined bot can't find the prefix 

I think its because database do not refresh i use it on quickmongo its works 
fix it
