### ISSUE TITLE
cant play music.

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#106]
When i try to play music (i tried with more than 40 songs) the error There was an error while searching: [SongName] 
[object, Object]

**Comment by taynotfound** [comment]
Same issue here

**Comment by taynotfound** [comment]
*seems to be only Spotify*

**Comment by Almazmsi** [comment]
> When i try to play music (i tried with more than 40 songs) the error There was an error while searching: [SongName] [object, Object]

check spotify code. and fix dashboard.spotify

**Comment by builtbyjonas** [comment]
> 

spotify does not work too

**Comment by builtbyjonas** [comment]
> > When i try to play music (i tried with more than 40 songs) the error There was an error while searching: [SongName] [object, Object]
> 
> check spotify code. and fix dashboard.spotify

i have, still same error

**Comment by Tomato6966** [comment]
it's an issue with your LAVALINK CONFIGURATION.
check the lavalink logs in your terminal where u host ur lavalink...

*don't trust "free" lavalink servers if u cant control it..*

**Comment by Tomato6966** [comment]
playing music has nothing to do with getting the resources!

Lavalink is searching them for you.

and then passing it back into it to play it!
however. if ur lavalink is not working, no audio will pop up!

so fix ur lavalink!
the bot is working.
