### ISSUE TITLE
Pls FIX premium commands. (!24/7; !afk)

### ISSUE THREAD

**Issue by KasaiKonoru** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#11]
![grafik](https://user-images.githubusercontent.com/45830738/109403287-96452c80-795c-11eb-8c1c-11d0c9f69a8a.png)

> 
> 
> Is the bot playing?

**Comment by Tomato6966** [comment]
What- why dont i get it?

**Comment by Tomato6966** [comment]
Is the bot playing?

**Comment by KasaiKonoru** [comment]
Im only in voice channel

**Comment by KasaiKonoru** [comment]
I hoped I can remove the errors with cache.get..... but in guild/message.js there are some errors I think

**Comment by Tomato6966** [comment]
Most errors like post / delete errors you can ignore that is coming from the request channel

but your saying the afk cmd doesnt work if the bot is playing something?

**Comment by KasaiKonoru** [comment]
> 
> 
> Most errors like post / delete errors you can ignore that is coming from the request channel
> 
> but your saying the afk cmd doesnt work if the bot is playing something?

Yes, if the bot is not playing and playing. Does not matter

**Comment by Tomato6966** [comment]
I couldnt find any errors from the source code imma test it out in the next day and give u information once i fixed it sorry

**Comment by KasaiKonoru** [comment]
> I couldnt find any errors from the source code imma test it out in the next day and give u information once i fixed it sorry

yes only run with this code
!afk user or! afk guild

**Comment by KasaiKonoru** [comment]
OK, I downloaded your new source code but its the afk.js

![grafik](https://user-images.githubusercontent.com/45830738/109416684-09cc5580-79c0-11eb-9579-aae102dd9798.png)

**Comment by Tomato6966** [comment]
That line is right

**Comment by Tomato6966** [comment]
I said give me time

**Comment by KasaiKonoru** [comment]
> I said give me time

Ok thank you so much.

**Comment by Tomato6966** [comment]
Fixxed in todays release update https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/releases/tag/4.0.0

well i literally downloaded github's code and it worked so....................... u can watch it on my live stream at the end... https://youtu.be/_qyHqucO_wc
