### ISSUE TITLE
VERY NICE Bot

### ISSUE THREAD

**Issue by Ezzyyr** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#12]
Can anyone say me: Why doesn't `!Afk` and `!24/7` work?
Im new in Javascript

**Comment by Tomato6966** [comment]
What do u mean with dosnt work, for me it does btw I updated the source code maybe that fixxed your problem?

**Comment by Tomato6966** [comment]
Episode 9 will be seek forward and rewind
Episode 10 will be now playing with a bar creation
Episode 11 will cover filters
Episode 12 lyrics
Episode 13 searching with youtube
Episode 14 searching with soundcloud
Episode 15 reactions
Episode 16 spotify playlist
Episode 17 handy distube settings
Episode 18 cookies 
Episode 19... 

Maybe sometime i will add request feature channel (like #distube-music)
