### ISSUE TITLE
Giving error after kicked manually

### ISSUE THREAD

**Issue by TechnoHaX** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#124]
Hi 
Like 2 weeks ago my bot started to bug when someone kicked it while it was in the VC. When you tried to start play something again (or any channel related command) it said that it's in another channel as you can see it on the screenshot. It was in all of the servers, so I think it's discord code related issue.
![image_2022-12-14_184641642](https://user-images.githubusercontent.com/64469529/207669142-1f66cea6-6cee-4dd1-b1a8-019dd6752959.png)

**Comment by KasaiKonoru** [comment]
I found it out:
    .on("playerDisconnect", async (player) => {
      if (player) return player.destroy()
    })

**Comment by KasaiKonoru** [comment]
I never knew that there's a playerDisconnect event lol.
I found it out while looking into the module files from erela.js

**Comment by TechnoHaX** [comment]
> I never knew that there's a playerDisconnect event lol. I found it out while looking into the module files from erela.js

Oh okay. And where do I find this string exactly?

**Comment by KasaiKonoru** [comment]
which string?

**Comment by KasaiKonoru** [comment]
playerMove event only triggers now when you move it. No disconnects anymore.
My old was:

if (!newChannel) return player.destroy()

**Comment by TechnoHaX** [comment]
I mean how do I fix this error? Which file do I need to edit?

**Comment by KasaiKonoru** [comment]
In your file where the events are. Add this:

.on("playerDisconnect", async (player) => {
if (player) return player.destroy()
})

**Comment by TechnoHaX** [comment]
I'm trying but it doesn't work. 
Is this the correct file to put it to? https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/blob/v13/events/guild/voiceStateUpdate.js

**Comment by KasaiKonoru** [comment]
> 

not in this file. Put it inb the file where you have all player events!

**Comment by KasaiKonoru** [comment]
https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/blob/v13/handlers/erela_events/events.js

**Comment by bullshark07** [comment]
It doesn’t happen to you that when you play a music the bot joins the channel but it doesn’t play the song and you have to take it out of the channel and rejoin it and everything works fine there?

**Comment by TechnoHaX** [comment]
It happens in two situation. One is when you kick it manually. (It's not detecting the kick event) Also if you pull it to other VC and than back, it bugs. 
I'm not sure about the second version but it's happening when the bot leaves automatically for some reason but it's not stopping the player.

**Comment by TechnoHaX** [comment]
I can only fix it with the slash stop command.

**Comment by TechnoHaX** [comment]
> It doesn’t happen to you that when you play a music the bot joins the channel but it doesn’t play the song and you have to take it out of the channel and rejoin it and everything works fine there?

But wait. Do you even get the bug that I mentioned above?

**Comment by TechnoHaX** [comment]
Ahh okay that fixed it! Thank you KasaiKonoru!

**Comment by bullshark07** [comment]
> I can only fix it with the slash stop command.

How could you fix it?
Can you help me?

**Comment by TechnoHaX** [comment]
You need to put the above mentioned comment to the erela events file. 
But I will make a commit today or tomorrow and you can download the fixed file if you can't fix it yourself.

**Comment by bullshark07** [comment]
> You need to put the above mentioned comment to the erela events file. 
> 
> But I will make a commit today or tomorrow and you can download the fixed file if you can't fix it yourself.

I meant that how did you fix the stop command?

**Comment by TechnoHaX** [comment]
The stop command works fine for me. I fixed the error when you kick it manually or the bot leaves by itself.

**Comment by TechnoHaX** [comment]
> > You need to put the above mentioned comment to the erela events file.
> > But I will make a commit today or tomorrow and you can download the fixed file if you can't fix it yourself.
> 
> I meant that how did you fix the stop command?

I made a pull request. You can download the fixed event file. That will fix the error.
