### ISSUE TITLE
SONG CRASHED

### ISSUE THREAD

**Issue by S1mp1yDucky** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#133]
![image](https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/assets/33154919/e115eeda-16cf-437a-8a5f-a897ddb9bdfa)

It keeps crashing? any solution cuz im stuck here,

**Comment by Tomato6966** [comment]
That's an issue on your lavalink server.
generally youtube isn't working well atm
