### ISSUE TITLE
Undefined in progress bar (requests only channel)

### ISSUE THREAD

**Issue by lambor590** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#21]
When a song starts, the progress bar is created, but the brackets are replaced with "undefined" instead showing a bracket. See the gif please, so you can uderstand it better.

![Gif of the demostration](https://user-images.githubusercontent.com/58952269/113410962-e9275f00-93b4-11eb-9701-be6769840ac8.gif)

**Comment by Tomato6966** [comment]
Is that from the Custom Emoji tab?
then edit emojis.json...

**Comment by lambor590** [comment]
Yes, but how can I replace it, or I just leave it empty?
![image](https://user-images.githubusercontent.com/58952269/113411991-766bb300-93b7-11eb-996e-2defaa5362ac.png)

**Comment by lambor590** [comment]
I tried replacing it with an emoji, but the right indicator still says undefined

**Comment by lambor590** [comment]
Also, when I play a song, always shows "couldn't delete message this is a catch to prevent a crash" in the console

**Comment by Tomato6966** [comment]
If u would be able to read and understand then u know that u can ignore this

**Comment by Tomato6966** [comment]
> Yes, but how can I replace it, or I just leave it empty?
> ![image](https://user-images.githubusercontent.com/58952269/113411991-766bb300-93b7-11eb-996e-2defaa5362ac.png)

In the custom emoji emojis.json u have 5 parameters or 6

**Comment by lambor590** [comment]
I have exactly what is provided by default in the repo

**Comment by Tomato6966** [comment]
Fixxed in latest updates
