### ISSUE TITLE
can you help me!

### ISSUE THREAD

**Issue by discordlite1** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#24]
Heyy Mr.Tomato I having som issues can you help me fix it out?
![image](https://user-images.githubusercontent.com/76547508/115654003-70377980-a35a-11eb-9174-796ce07e1801.png)

**Comment by m4kuwu** [comment]
the lavalink node doesn't start cause port 2333 is in use, change it to one that is not being used
