### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by m4kuwu** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#25]
I have entered all the data of the spotify client
any idea what it might be?

discord:
![image](https://user-images.githubusercontent.com/80482255/116554877-54375900-a8c1-11eb-94f4-56638c266f3a.png)

terminal:
![image](https://user-images.githubusercontent.com/80482255/116555318-dc1d6300-a8c1-11eb-92f3-2d43902369ec.png)

**Comment by Tomato6966** [comment]
remove the things after and including the ? of the URL cause it cannot access that ...

**Comment by m4kuwu** [comment]
I did it but it still gives error, I even tried to use the spotify URI but it did not leave, could it be a problem in the code or something like that? Or is it just me who has the problem

**Comment by Tomato6966** [comment]
send me the link please

**Comment by m4kuwu** [comment]
Okay, after reading any errors that I had missed, I checked the config file of the bot and found that the clientID and clientSecret were inverted, not realizing that they were inverted I put them as is.

My mistake, now if the songs work. Thanks for the code!
