### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by arararat** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#28]
When I applied earrape filter and after sometime when I try to to remove it by the commands it was not remove I tried many times but filter was not removing

**Comment by arararat** [comment]
At least reply

**Comment by Tomato6966** [comment]
clearfilter is a thing too

**Comment by Bedrock16** [comment]
Yes it is a command

**Comment by Bedrock16** [comment]
> clearfilter is a thing too

**Your main bot (Lava music) has many filters but the repo only has 2 filters please add bro other wise your bot is op!!!!**
