### ISSUE TITLE
Filters issue

### ISSUE THREAD

**Issue by Bedrock16** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#29]
**Your main bot (Lava music) has many filters but the repo only has 2 filters please add bro other wise your bot is op!!!!**

**Comment by jaypm123** [comment]
> **Your main bot (Lava music) has many filters but the repo only has 2 filters please add bro other wise your bot is op!!!!**

check out `with-filters` branch of the repo
https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/tree/with-filters
