### ISSUE TITLE
The bot music commands are not working quite well.

### ISSUE THREAD

**Issue by SCkarma12** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#37]
Hi, I really love the but but there is just 1 issue. The bot is coming online correctly, but all commands are working except for the music commands. The play command won't nor any of the others. I don't know if this is a error I made (which it shouldn't cause all I configured was the token). Hopefully you are able to help me with this.

No errors were logged in the console.  But I do have questions for the image below. Is this what could be affecting the bot?
![image](https://user-images.githubusercontent.com/85044889/126883302-706b605d-f203-4aa0-9c57-f482f61ef673.png)

**Comment by Tomato6966** [comment]
read README
and start lavalink

**Comment by Bedrock16** [comment]
It seems like you are using lavalink 

Use this lavalink node 
Host - lava.link 
Port - 80 
Password - Anything as a password 

Just fill this out in the config file and restart the bot it will work

**Comment by Tomato6966** [comment]
use loclahost
the password ofc must be the same password as the host needs it!

**Comment by Bedrock16** [comment]
Bro I think he is running bot on repl.it ..... So he can't host lavalink and bot on same repl
