### ISSUE TITLE
Need Help Pls - What can I do?

### ISSUE THREAD

**Issue by KasaiKonoru** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#4]
ownerIDS is not defined with !requestpremium

**Comment by Tomato6966** [comment]
Imma fix that in 1hour

**Comment by Tomato6966** [comment]
https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/blob/main/commands/%F0%9F%92%B0%20Premium/requestpremium.js
Fixed with new update, one letter was missing
