### ISSUE TITLE
Multiple Voice Channels

### ISSUE THREAD

**Issue by Sikksens** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#43]
Hello,

Just wanted to find out if it's possible to get the bot to join any voice channel a requester is in when using the unique music setup, so still having the dedicated text channel as is but the bot isn't limited to the created voice channel.

**Comment by Tomato6966** [comment]
it is just change the code ab it

**Comment by WoofWolfGG** [comment]
@Sikksens Many thanks to you!
