### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SxMAbel** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#48]
C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13>npm i
npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code 1
npm ERR! path C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13\node_modules\@discordjs\opus
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR!   opus_multistream.c
npm ERR! c:\users\abelp\desktop\discord-js-lavalink-music-bot-erela-js-13\node_modules\@discordjs\opus\deps\opus\src\opus_multistream.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13\node_modules\@discordjs\opus\build\deps\libopus.vcxproj]
npm ERR! Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\abelp\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13\node_modules\@discordjs\opus\prebuild\node-v93-napi-v3-win32-ia32-unknown-unknown\opus.node --module_name=opus --module_path=C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13\node_modules\@discordjs\opus\prebuild\node-v93-napi-v3-win32-ia32-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.4.1
npm ERR! node-pre-gyp info using node@16.6.2 | win32 | ia32
npm ERR! node-pre-gyp info check checked for "C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13\node_modules\@discordjs\opus\prebuild\node-v93-napi-v3-win32-ia32-unknown-unknown\opus.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v93-napi-v3-win32-ia32-unknown-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v93-napi-v3-win32-ia32-unknown-unknown.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.6.0 and node@16.6.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v93-napi-v3-win32-ia32-unknown-unknown.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.6.2 | win32 | ia32
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.6.2 | win32 | ia32
npm ERR! gyp info find Python using Python version 3.9.7 found at "C:\Python39\python.exe"
npm ERR! gyp info find VS using VS2017 (15.9.28307.1684) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python39\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\abelp\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\abelp\\Desktop\\discord-js-lavalink-Music-Bot-erela-js-13\\node_modules\\@discordjs\\opus\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\abelp\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\abelp\\AppData\\Local\\node-gyp\\Cache\\16.6.2\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\abelp\\AppData\\Local\\node-gyp\\Cache\\16.6.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\abelp\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\abelp\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.6.2\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\abelp\\Desktop\\discord-js-lavalink-Music-Bot-erela-js-13\\node_modules\\@discordjs\\opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\abelp\\Desktop\\discord-js-lavalink-Music-Bot-erela-js-13\\node_modules\\@discordjs\\opus\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.6.2 | win32 | ia32
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=Win32'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\abelp\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\abelp\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\abelp\\Desktop\\discord-js-lavalink-Music-Bot-erela-js-13\\node_modules\\@discordjs\\opus\\prebuild\\node-v93-napi-v3-win32-ia32-unknown-unknown\\opus.node" "--module_name=opus" "--module_path=C:\\Users\\abelp\\Desktop\\discord-js-lavalink-Music-Bot-erela-js-13\\node_modules\\@discordjs\\opus\\prebuild\\node-v93-napi-v3-win32-ia32-unknown-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13\node_modules\@discordjs\opus
npm ERR! gyp ERR! node -v v16.6.2
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\abelp\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13\node_modules\@discordjs\opus\prebuild\node-v93-napi-v3-win32-ia32-unknown-unknown\opus.node --module_name=opus --module_path=C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13\node_modules\@discordjs\opus\prebuild\node-v93-napi-v3-win32-ia32-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13\node_modules\@discordjs\node-pre-gyp\lib\util\compile.js:85:20)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19043
npm ERR! node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\abelp\\Desktop\\discord-js-lavalink-Music-Bot-erela-js-13\\node_modules\\@discordjs\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\abelp\Desktop\discord-js-lavalink-Music-Bot-erela-js-13\node_modules\@discordjs\opus
npm ERR! node-pre-gyp ERR! node -v v16.6.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.4.1
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abelp\AppData\Local\npm-cache\_logs\2021-11-12T11_02_05_604Z-debug.log

**Comment by Tomato6966** [comment]
install nodejs and npm right

suggestion:
Use `nodejs v16.13.0` instead of something higher
