### ISSUE TITLE
Sry for that but there are many errors

### ISSUE THREAD

**Issue by KasaiKonoru** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#5]
![grafik](https://user-images.githubusercontent.com/45830738/109149453-de4f2e00-7767-11eb-82ee-6add4c0e5a40.png)

**Comment by Tomato6966** [comment]
Dude if u change the code its ur fault
And only look at red errors
Grey errors or yellow errors are just informations that something didnt work because of guild/user settings lije if he doesnt accept dms, as here...
Or if he try to delete a message which doesnot exist etc

**Comment by Tomato6966** [comment]
Should be fixxed too as on the other issue you opened
