### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bedrock16** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#53]
https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/blob/283e55a18a7b33ff1a7404aac8b4d370b89d3dd9/events/client/shardReady.js#L3

What is ```client.logger``` here it's giving error when I try to run bot

**Comment by Bedrock16** [comment]
![Uploading Screenshot_2021-11-14-14-41-32-642_com.android.chrome.jpg…]()

**Comment by Tomato6966** [comment]
Thanks

**Comment by Tomato6966** [comment]
Makes no sense tho it's in extraevents

**Comment by Bedrock16** [comment]
> Makes no sense tho it's in extraevents

Wdym?

**Comment by Bedrock16** [comment]
@Tomato6966 did you fixed that?

**Comment by Tomato6966** [comment]
its working dont update a few files, update all
