### ISSUE TITLE
Embed Color

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#55]
I dont know how I can change the embed color. Everytime I try to paste "BLURPLE" in and use the help command then the help command embed backround is still orange (I also tryed to paste an hex color code in)

**Comment by DevClayy** [comment]
Have you gone to 
```botconfig/embed.json```

and changed it there?

Otherwise go to the specific command file and see if the color varies from what embed.json has.
