### ISSUE TITLE
Slash Commands Are Not Loading On REPL.IT (deploy)

### ISSUE THREAD

**Issue by AkshatP-Dev** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#56]
IF I use the command --> +deploy [GUILD_ID] , It should load all the slash commands instantly, even if it's not instant, I waited for more than 1 hour and tried again by starting the bot again but I'm facing an error I guess.

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/92432892/143777554-fabb82ac-99ef-4dac-9acf-1281a42545d7.png">

**Comment by Tomato6966** [comment]
invite your bot with the applications.commands invite link in oauth2
![image](https://i.imgur.com/gOfEBrT.png)
