### ISSUE TITLE
Slash Commands Are Deployed But Not Working

### ISSUE THREAD

**Issue by AkshatP-Dev** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#58]
Only the invite command is working fine, the rest are taking a lot of time to work, infact they're not working at all.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/92432892/143876162-da2ab541-42e9-4dec-9c0a-98bb410ff09d.png">

**Comment by Tomato6966** [comment]
they should work i didnt test i also dont have the time currently to see what's causing the problem, sorry

**Comment by AkshatP-Dev** [comment]
> they should work i didnt test i also dont have the time currently to see what's causing the problem, sorry

Okay, but please look into it whenever you got time ;(
