### ISSUE TITLE
Oh nice, thx that you fixed it. I want to be your beta tester ^^ I love your bot <3

### ISSUE THREAD

**Issue by KasaiKonoru** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#6]
ah oh
**WAIT**
uptime command: duration is not defined

**Comment by Tomato6966** [comment]
Will do later too^^

**Comment by KasaiKonoru** [comment]
> 
> 
> Will do later too^^

nice, thx

**Comment by Tomato6966** [comment]
https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/blob/main/commands/🔰%20Info/uptime.js fixxed
