### ISSUE TITLE
What do I have to do at config.json in spotify

### ISSUE THREAD

**Issue by ArithmosPrtgn** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#61]
Hi, I want to know what do I need to know what I do at botconfig > config.json at: `   "spotify": {
      "clientID": "",
      "clientSecret": ""
   }
}`

**Comment by Tomato6966** [comment]
either leave EMPTY or go to: developers.spotify.com --> login (free) --> Dashboard --> Create App (free) and paste in the values, to support spotify!
