### ISSUE TITLE
Replit Host

### ISSUE THREAD

**Issue by LOGODERKING** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#67]
I cant keep the Bot online in Replit i can start it and normaly use it but if i close the website and i want that the bot is 24/7 it gets offline although i added the website link of the bot to a uptimer link system.
![image](https://user-images.githubusercontent.com/85257897/147389415-d4416984-1cb7-4c9f-a508-fd523572345a.png)

**Comment by Tomato6966** [comment]
add an uptimer system which works good

**Comment by LOGODERKING** [comment]
I did it worked but since tuesday it doesn't work anymore i used that one yoh added to the html website
