### ISSUE TITLE
Replit Host

### ISSUE THREAD

**Issue by LOGODERKING** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#68]
I did it worked but since tuesday it doesn't work anymore i used that one yoh added it to uptimerobot.com so that one that you added tio the keep-alive.js file

**Comment by Tomato6966** [comment]
it works for me

**Comment by LOGODERKING** [comment]
yeah for you but not for me how can i fix that?

**Comment by Akshit1025** [comment]
> yeah for you but not for me how can i fix that?

which node version are you using in your repl.it

**Comment by LOGODERKING** [comment]
Version: v12.22.6

**Comment by Akshit1025** [comment]
> Version: v12.22.6

that is why it is not working
it should be version 16 + for discord.js v13 to work properly

**Comment by LOGODERKING** [comment]
i upgraded the node version to v16.13.1 but i can still not start the bot over the keep-alive-server.js
