### ISSUE TITLE
err

### ISSUE THREAD

**Issue by Abdo30004** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#7]
![image](https://user-images.githubusercontent.com/76871067/109162398-735a2300-7778-11eb-97ba-e5514a765a45.png)
i don not know the solution

**Comment by KasaiKonoru** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/76871067/109162398-735a2300-7778-11eb-97ba-e5514a765a45.png)
> i don not know the solution

install new

**Comment by Tomato6966** [comment]
The solution is to reinstall all packages and before that make sure u have all needed components
