### ISSUE TITLE
TimeoutOverflowWarning

### ISSUE THREAD

**Issue by PatalJunior** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#73]
**If the queue has a very long music, it can overflow the timeout, making the button only able to be pressed 1 time, because NodeJS sets the Timeout to 1ms.**

**The fix could be, just make the timeout variable use seconds instead of milliseconds, and at the end multiply it by a 1000**

![image](https://user-images.githubusercontent.com/81658559/147882552-5a8065dc-1846-4d1a-a4cc-f7d588ded94e.png)

![image](https://user-images.githubusercontent.com/81658559/147882617-a0573760-6773-4b9f-af38-42b62844e80f.png)

**And, now I just realized that the time that the music duration, has a wrong hh:mm:ss format, and goes past 60 minutes.**

**Comment by Tomato6966** [comment]
Thanks for your report i will check that

**Comment by Tomato6966** [comment]
Fixxed both in new updating releasing now!
