### ISSUE TITLE
Load is stuck

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#74]
Hello can someone help me pls

When I start the bot then the programm goes stuck at: 
![Screenshot_20220104-102218_Firefox](https://user-images.githubusercontent.com/81481526/148037428-83951b9a-5686-45c7-b92e-7e3c5e438509.jpg)

Version: Replit

**Comment by Tomato6966** [comment]
if ur hosting on replit add those lines in index:
```js
client.on("warn", console.log)
client.on("debug", console.log)
client.on("rateLimit", console.log)
```

I assume ur ip is banned from 429 (replit shares ips,....)
