### ISSUE TITLE
Bot not responsing

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#75]
after a few hours the bot no longer response to the commands and song requests,  did someone knows how to fix it? 

Pls help

Version: Replit

**Comment by Tomato6966** [comment]
make sure to host ur bot 24/7 on replit with an uptimer or hacker plan...

**Comment by builtbyjonas** [comment]
Yeah but I mean the bot does not response to the commands and song requests although it is online and the code is also online.

**Comment by builtbyjonas** [comment]
My bot is already 24/7 hosted
