### ISSUE TITLE
bot not responding

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#76]
after a few hours the bot no longer response to the commands and song requests but the bot is online and the code too, did someone knows how to fix it?

Pls help

Version: Replit

Note: bot is 24/7 hosted with uptimerobot

**Comment by builtbyjonas** [comment]
I think it i is an connection timeout

**Comment by builtbyjonas** [comment]
the bot no longer response to the commands and the song requests after 10 -13 hours uptime

**Comment by testbot-github** [comment]
> the bot no longer response to the commands and the song requests after 10 -13 hours uptime

I think it is because of "inactivity".
If your bot is not active, discord makes it offline or somethin ig?
The best ideal way to fix this is by adding a changing status.

**Comment by builtbyjonas** [comment]
yeah but the changing status isn't changing

**Comment by builtbyjonas** [comment]
After the first status the bot switches to the second status but after the second status the bot didnt change back to the first
