### ISSUE TITLE
bot not responding

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#78]
The bot does not response after an time and when someone runs an command then the console says this: 
![Screenshot_20220106-155657_Firefox](https://user-images.githubusercontent.com/81481526/148402664-75503bfe-ac98-4841-8ac9-52e2f8203335.jpg)

How to fix it? Pls help

Version: Replit

**Comment by jerry-619** [comment]
Ratelimit wait sometime

**Comment by builtbyjonas** [comment]
How can I change the rate limit?

**Comment by jerry-619** [comment]
> 

You can't change it :(

**Comment by Tomato6966** [comment]
it's because of replit no source error, swap the host to a host which doesn't share the ips for example
[https://bero.milrato.dev](https://bero.milrato.dev) and use the code: `milrato`
