### ISSUE TITLE
Status Not Changing

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#79]
The bot does not change from first to second status text and I think not from second to first

Pls help
Version: replit

**Comment by testbot-github** [comment]
@JanjyTapYT Are there any errors in the console?

**Comment by builtbyjonas** [comment]
@testbot-github No only the Message "Set First Status Text" all the time

**Comment by testbot-github** [comment]
> @testbot-github No only the Message "Set First Status Text" all the time

Oh...
Idk how to fix that error, so u gotta wait for @Tomato6966 to respond.
