### ISSUE TITLE
Addition of Dislikes 

### ISSUE THREAD

**Issue by Johannes7k75** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#84]
add dislikes via a dislike api.
Like the returnyoutubedislikeapi

https://www.returnyoutubedislike.com/docs/fetching

https://returnyoutubedislikeapi.com/votes?videoid=VdHmgkkVYec

**Comment by Tomato6966** [comment]
I don#t like to add something like this as lavalink is not used for scraping song data, just the opus what's the reason of youtube not beeing able to fully delete lavalink
