### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by builtbyjonas** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#88]
When I start my bot then it shows this:
![Screenshot_20220127-162243_Chrome](https://user-images.githubusercontent.com/81481526/151389289-400fb37d-dc30-4e25-9e98-a35afc910b78.jpg)

@Tomato6966 pls help

**Comment by TheGamer3514** [comment]
same

**Comment by heyfolk** [comment]
If you're hosting with replit then delete database files and run again project

**Comment by MRJ-Badshah** [comment]
Node 16 + required

**Comment by builtbyjonas** [comment]
> If you're hosting with replit then delete database files and run again project

Ok I try it in the evening

**Comment by builtbyjonas** [comment]
> Node 16 + required

Node v16 is installed but ty
