### ISSUE TITLE
Playlist error with Spotify

### ISSUE THREAD

**Issue by heyfolk** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#89]
I've only been facing one problem :/ When I put my playlist to play, instead of playing the official song, it takes songs from rehearsals, or concerts, with low quality, and that gets in the way too much :c

**Comment by builtbyjonas** [comment]
You have to make env variables called clientID and clientSecret and fill them out with the spotify client id and client secret.

You can configure it out in the botconfig/config.json there you can fill this out there too

**Comment by Tomato6966** [comment]
As janjytapyt explained^^
