### ISSUE TITLE
I find another error: Sorry xD

### ISSUE THREAD

**Issue by KasaiKonoru** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#9]
![grafik](https://user-images.githubusercontent.com/45830738/109215951-2c8a1e80-77b4-11eb-942a-ff55ee6f0d36.png)

**When I used "!afk user"**

... and
![grafik](https://user-images.githubusercontent.com/45830738/109216271-9c000e00-77b4-11eb-9832-e515bc833494.png)

**When I used "!settings"**

**Comment by Tomato6966** [comment]
You can savely ignore the error, which just comes if he cant find the settings channel, if u set it up tho reinstall all databases
