### ISSUE TITLE
Error unmute

### ISSUE THREAD

**Issue by RomainHartmann** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#90]
I use discord-js-lavalink-Music-Bot-erela-js but I have a problem. When I unmute it there is a little bug in the music. Can you help me?

https://user-images.githubusercontent.com/86157775/151676212-37545060-d903-4217-a20b-0178de1a2c35.mp4

**Comment by Tomato6966** [comment]
I can't fix it currently, sorry
