### ISSUE TITLE
Lavalink problem

### ISSUE THREAD

**Issue by MRJ-Badshah** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#91]
Lavalink not connecting. @Tomato6966 
Pls help me

**Comment by builtbyjonas** [comment]
Go to the botconfig/config.json and remove the node01.lavalink.eu and paste in lavalink.eu

**Comment by Tomato6966** [comment]
read readme

**Comment by MRJ-Badshah** [comment]
I connects but not all time, I used my one but same problem.eg: after 10 tries Connect 1 time.
