### ISSUE TITLE
Not able to change Lavalink

### ISSUE THREAD

**Issue by LOGODERKING** [Tomato6966/discord-js-lavalink-Music-Bot-erela-js#96]
If i change the lavalink server in the config.json file, the bot still tries to connect to node01.lavalink.eu. How can i fix that?

**Comment by M4riosDev** [comment]
first save the changed lavalink server and ........ Put it have again error put thes lava.link port 80 password : pass

**Comment by Almazmsi** [comment]
> If i change the lavalink server in the config.json file, the bot still tries to connect to node01.lavalink.eu. How can i fix that?

use lavalink server 3
 "clientsettings": {
      "nodes": [
         {
            "host": "node03.lavalink.eu",
            "port": 2333,
            "password": "Raccoon"
         }
      ]
   }

**Comment by malbouy** [comment]
> 

Simply just do so in the code, and make sure you save the config file before restarting. 
Files: https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/blob/v13/handlers/erela_events/creation.js
Lines: 32

**Comment by Almazmsi** [comment]
> > 
> 
> Simply just do so in the code, and make sure you save the config file before restarting. Files: https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/blob/v13/handlers/erela_events/creation.js Lines: 32

hmm. 
Check https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js/issues/100
